@startuml Class
!include ../../styles/modern-style.plantuml
!include ../diagrams/class.plantuml
@enduml

@startuml Class2
!include ../../styles/modern-style.plantuml
!include ../diagrams/class2.plantuml
@enduml

@startuml Sequence
!include ../../styles/modern-style.plantuml
!include ../diagrams/sequence.plantuml
@enduml

@startuml UseCase
!include ../../styles/modern-style.plantuml
!include ../diagrams/usecase.plantuml
@enduml
