' This is a plantuml style file
' To use this style include it into your plantuml diagrams, e.g.:
' !include modern-style.plantuml

' Color schema
!$primaryColor = "#e0f9ff"
!$secondaryColor = "#cccccc"

' General settings
hide empty methods
hide empty attributes
skinparam {
    DefaultFontName Helvetica 
    RoundCorner 5
    Shadowing false

    ' Title Styling
    TitleFontSize 24
    TitleFontStyle Bold

    ' Class Diagrams
    CircledCharacterRadius 5
    CircledCharacterFontSize 8
    CircledCharacterFontColor Black
    Class {
        FontSize 16
        FontStyle Bold
        BackgroundColor $primaryColor
        BorderThickness 2
        BorderColor Black
        ArrowThickness 3
        ArrowColor Black
        AttributeIconSize 9
    }

    ' Sequence Diagrams
    Sequence {
        MessageAlign Center
        FontSize 16
        FontStyle Bold
        ParticipantBackgroundColor $primaryColor
        ParticipantBorderColor Black
        ParticipantFontStyle Bold
        BorderColor Black
        ArrowThickness 1.1
        ArrowColor Black
        LifeLineBorderThickness 1
        LifeLineBorderColor Black
        ActorBackgroundColor $primaryColor
        ActorBorderColor Black
        ActorBorderThickness 2
        ActorFontStyle Bold
    }

    ' UseCase Diagrams
    UseCase {
        FontSize 16
        FontStyle Bold
        BorderColor Black
        ArrowThickness 1.1
        ArrowColor Black
        ActorBackgroundColor $primaryColor
        BackgroundColor $primaryColor
        ActorBorderColor Black
        ActorBorderThickness 2
        ActorFontStyle Bold
    }

    ' Activity Diagrams
    Activity {
        BorderColor Black
        ArrowThickness 1.1
        ArrowColor Black
        BackgroundColor $primaryColor
    }

    ' Component Diagrams
    Component {
        BorderColor Black
        ArrowThickness 1.1
        ArrowColor Black
        BackgroundColor $primaryColor
    }
    InterfaceBackgroundColor $primaryColor
    InterfaceBorderColor Black

    ' State Diagrams
    State {
        BorderColor Black
        ArrowThickness 1.1
        ArrowColor Black
        BackgroundColor $primaryColor
    }

    ' Deployment Elements
    FrameBackgroundColor $primaryColor
    FrameBorderColor Black
    AgentBackgroundColor $primaryColor
    AgentBorderColor Black
    ArtifactBackgroundColor $primaryColor
    ArtifactBorderColor Black
    BoundaryBackgroundColor $primaryColor
    BoundaryBorderColor Black
    CardBackgroundColor $primaryColor
    CardBorderColor Black
    CloudBackgroundColor $primaryColor
    CloudBorderColor Black
    CollectionsBackgroundColor $primaryColor
    CollectionsBorderColor Black
    ControlBackgroundColor $primaryColor
    ControlBorderColor Black
    DatabaseBackgroundColor $primaryColor
    DatabaseBorderColor Black
    EntityBackgroundColor $primaryColor
    EntityBorderColor Black
    FileBackgroundColor $primaryColor
    FileBorderColor Black
    FolderBackgroundColor $primaryColor
    FolderBorderColor Black
    NodeBackgroundColor $primaryColor
    NodeBorderColor Black
    PackageBackgroundColor $primaryColor
    PackageBorderColor Black
    QueueBackgroundColor $primaryColor
    QueueBorderColor Black
    StackBackgroundColor $primaryColor
    StackBorderColor Black
    RectangleBackgroundColor $primaryColor
    RectangleBorderColor Black
    StorageBackgroundColor $primaryColor
    StorageBorderColor Black

    ' Notes
    Note {
        BackgroundColor $secondaryColor
        BorderThickness 1
        BorderColor White
        FontSize 10
    }
}

' title Class Example
' !include ../examples/diagrams/class.plantuml

' title Sequence Example
' !include ../examples/diagrams/sequence.plantuml

' title UseCase Example
' !include ../examples/diagrams/usecase.plantuml

' title Activity Example
' !include ../examples/diagrams/activity.plantuml

' title Component Example
' !include ../examples/diagrams/component.plantuml

' title State Example
' !include ../examples/diagrams/state.plantuml

' title Deployment Example
' !include ../examples/diagrams/deployment.plantuml


